server.port=9526
spring.application.name=icommerce
spring.datasource.url=jdbc:mysql://localhost:3306/mi_base?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=47564756
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
